# Generated by Django 6.1 on 2026-08-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tree_reports/')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('action_needed', 'Action Needed'), ('protected', 'Protected'), ('monitoring', 'Monitoring')], default='reported', max_length=20)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
