# Generated by Django 6.1 on 2026-08-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='progress_updates/')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('action_needed', 'Action Needed'), ('protected', 'Protected'), ('monitoring', 'Monitoring')], default='monitoring', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tree_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='reports.treereport')),
            ],
        ),
    ]
